image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "webide"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG'

default:
  before_script:
    - ls -lrth && pwd
  artifacts:
    expire_in: 72 hours 
    paths:
      - .local/detector
      - .local/lib
      - .local/bin
      - .local/include
      - .local/share
      - results
      - config
      - juggler.env
    reports:
      dotenv: juggler.env

stages:
  - config0
  - config
  - initialize
  - data_init
  - simulate
  - benchmarks
  - deploy

common:variables:
  stage: config0
  rules:
    - if: '$CI_SERVER_HOST == "eicweb.phy.anl.gov"' 
  script:
    - |
      echo "   CI_PIPELINE_SOURCE = ${CI_PIPELINE_SOURCE}"
      echo " COMMON_BENCH_VERSION = ${COMMON_BENCH_VERSION}"
      if [[ "${CI_PIPELINE_SOURCE}" == "push"  || "x${CI_PIPELINE_SOURCE}" == "xmerge_request_event"  || "$CI_COMMIT_BRANCH" == "master" ]]; then
        export COMMON_BENCH_VERSION="${CI_COMMIT_REF_NAME}"
        echo "COMMON_BENCH_VERSION = ${CI_COMMIT_REF_NAME}"
        echo "COMMON_BENCH_VERSION=${CI_COMMIT_REF_NAME}" >> juggler.env
      fi
      echo "COMMON_BENCH_VERSION = ${COMMON_BENCH_VERSION}"

common:setup:
  stage: config
  rules:
    - if: '$CI_SERVER_HOST == "eicweb.phy.anl.gov"' 
  needs: ["common:variables"]
  script:
    - git clone -b "${COMMON_BENCH_VERSION}" "${CI_REPOSITORY_URL}"  setup 
    - source setup/bin/env.sh && ./setup/bin/install_common.sh

common:detector:
  stage: initialize
  rules:
    - if: '$CI_SERVER_HOST == "eicweb.phy.anl.gov"' 
  needs: ["common:setup"]
  script:
    - source .local/bin/env.sh && build_detector.sh
    - bin/mkdir_local_data_link sim_output 
    - print_env.sh
    - ls -lrth

detector_benchmarks:
  stage: benchmarks
  rules:
    - if: '$CI_SERVER_HOST == "eicweb.phy.anl.gov"' 
  needs: ["common:variables"]
  variables:
    JUGGLER_DETECTOR: "athena"
    COMMON_BENCH_VERSION: "$COMMON_BENCH_VERSION"
  trigger:
    project: EIC/benchmarks/detector_benchmarks
    strategy: depend

    #physics_benchmarks:
    #  stage: benchmarks
    #  needs: ["common:variables"]
    #  variables:
    #    JUGGLER_DETECTOR: "athena"
    #    COMMON_BENCH_VERSION: "$COMMON_BENCH_VERSION"
    #  trigger:
    #    project: EIC/benchmarks/physics_benchmarks
    #    strategy: depend


pages:
  image: eicweb.phy.anl.gov:4567/containers/eic_container/alpine
  stage: deploy
  rules:
    - if: '$CI_SERVER_HOST == "gitlab.phy.anl.gov" && $CI_COMMIT_BRANCH == "master"' 
  script:
    - apk update && apk add doxygen  graphviz ttf-ubuntu-font-family
    - cd doc && doxygen Doxyfile  && cd ..
    - mkdir -p public && cp -r doc/docs/html/* public/.
    #    - mkdir build && cd build && cmake ../. -DCMAKE_INSTALL_PREFIX=../install && make doc_doxygen && cd ..
    #- cp -r build/doxygen_output/html public
  artifacts:
    paths:
    - public

